# Generated by Django 6.0 on 2025-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('question_count', models.IntegerField(default=1)),
                ('ponderation', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ponderaciones',
                'ordering': ['area', 'order', 'subject'],
                'indexes': [models.Index(fields=['area', 'order'], name='ponderacion_area_5a247e_idx')],
                'unique_together': {('area', 'subject')},
            },
        ),
    ]
