# Generated by Django 6.0 on 2026-03-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
        ('ponderaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ponderacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ponderacion',
            name='convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponderaciones', to='convocatorias.convocatoria'),
        ),
        migrations.AlterUniqueTogether(
            name='ponderacion',
            unique_together={('convocatoria', 'area', 'subject')},
        ),
        migrations.AddIndex(
            model_name='ponderacion',
            index=models.Index(fields=['convocatoria', 'area'], name='ponderacion_convoca_20ddf7_idx'),
        ),
    ]
