# Generated by Django 6.0 on 2026-06-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderaciones', '0004_remove_convocatoria_fk'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 0004 already removes the physical index together with the FK column.
            # Keep Django's migration state in sync without dropping it twice.
            state_operations=[
                migrations.RemoveIndex(
                    model_name='ponderacion',
                    name='ponderacion_convoca_20ddf7_idx',
                ),
            ],
            database_operations=[],
        ),
        migrations.RenameIndex(
            model_name='plantillaitem',
            new_name='plantilla_i_plantil_f50d09_idx',
            old_name='plantilla_items_order_idx',
        ),
        migrations.RenameIndex(
            model_name='plantillaponderacion',
            new_name='plantillas__area_fd2a95_idx',
            old_name='plantillas_area_idx',
        ),
    ]
