# Generated by Django 6.0 on 2026-03-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'convocatorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatFormatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_length', models.IntegerField(default=21)),
                ('answers_length', models.IntegerField(default=60)),
                ('litho_offset', models.IntegerField(default=0)),
                ('litho_length', models.IntegerField(default=6)),
                ('tipo_offset', models.IntegerField(default=6)),
                ('tipo_length', models.IntegerField(default=1)),
                ('dni_offset', models.IntegerField(default=7)),
                ('dni_length', models.IntegerField(default=8)),
                ('aula_offset', models.IntegerField(default=15)),
                ('aula_length', models.IntegerField(default=3)),
                ('answers_offset', models.IntegerField(default=18)),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dat_format', to='convocatorias.convocatoria')),
            ],
            options={
                'db_table': 'dat_format_configs',
            },
        ),
        migrations.CreateModel(
            name='CalificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('correct_value', models.DecimalField(decimal_places=3, default=10, max_digits=8)),
                ('incorrect_value', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('blank_value', models.DecimalField(decimal_places=3, default=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calification_configs', to='convocatorias.convocatoria')),
            ],
            options={
                'db_table': 'calification_configs',
                'unique_together': {('convocatoria', 'area_name')},
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_count', models.IntegerField(default=60)),
                ('vacantes', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='convocatorias.convocatoria')),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['convocatoria', 'order', 'name'],
                'unique_together': {('convocatoria', 'name')},
            },
        ),
    ]
