# Generated by Django 6.0 on 2026-06-15 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_remove_convocatoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('paterno', models.CharField(blank=True, max_length=100)),
                ('materno', models.CharField(blank=True, max_length=100)),
                ('nombres', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('programa', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos_padron', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidatos_padron',
                'ordering': ['paterno', 'materno', 'nombres', 'dni'],
                'indexes': [models.Index(fields=['created_by', 'dni'], name='candidatos__created_84e9a6_idx'), models.Index(fields=['created_by', 'area'], name='candidatos__created_e59eec_idx'), models.Index(fields=['created_by', 'programa'], name='candidatos__created_3b7b1e_idx')],
                'unique_together': {('created_by', 'client_id')},
            },
        ),
    ]
