# Generated by Django 6.0 on 2026-06-15 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_identifiersource_identifierrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('total_lines', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'response_sources',
                'ordering': ['-timestamp', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResponseRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('header', models.CharField(blank=True, max_length=80)),
                ('lectura', models.CharField(blank=True, max_length=40)),
                ('exam_code', models.CharField(blank=True, max_length=40)),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('indicator', models.CharField(blank=True, max_length=10)),
                ('litho', models.CharField(blank=True, max_length=40)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('answers', models.CharField(blank=True, max_length=300)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('source_client_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_rows', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='convocatorias.responsesource')),
            ],
            options={
                'db_table': 'response_rows',
                'ordering': ['lectura', 'dni', 'client_id'],
            },
        ),
        migrations.AddIndex(
            model_name='responsesource',
            index=models.Index(fields=['created_by', 'timestamp'], name='response_so_created_02e608_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responsesource',
            unique_together={('created_by', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='responserow',
            index=models.Index(fields=['created_by', 'dni'], name='response_ro_created_3f7e27_idx'),
        ),
        migrations.AddIndex(
            model_name='responserow',
            index=models.Index(fields=['created_by', 'litho'], name='response_ro_created_1cdbed_idx'),
        ),
        migrations.AddIndex(
            model_name='responserow',
            index=models.Index(fields=['created_by', 'source_client_id'], name='response_ro_created_68649d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responserow',
            unique_together={('created_by', 'client_id')},
        ),
    ]
