# Generated by Django 6.0 on 2026-06-15 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_responsesource_responserow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKeySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('identification_name', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('area', models.CharField(blank=True, max_length=100)),
                ('valid_rows', models.IntegerField(default=0)),
                ('response_errors', models.IntegerField(default=0)),
                ('identification_errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_key_sources',
                'ordering': ['-timestamp', 'area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnswerKeyRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('answers', models.CharField(blank=True, max_length=300)),
                ('indicator', models.CharField(blank=True, max_length=10)),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('litho', models.CharField(blank=True, max_length=40)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('source_client_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_rows', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='convocatorias.answerkeysource')),
            ],
            options={
                'db_table': 'answer_key_rows',
                'ordering': ['area', 'tipo', 'client_id'],
            },
        ),
        migrations.AddIndex(
            model_name='answerkeysource',
            index=models.Index(fields=['created_by', 'area'], name='answer_key__created_01919f_idx'),
        ),
        migrations.AddIndex(
            model_name='answerkeysource',
            index=models.Index(fields=['created_by', 'timestamp'], name='answer_key__created_cbb8b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerkeysource',
            unique_together={('created_by', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='answerkeyrow',
            index=models.Index(fields=['created_by', 'area', 'tipo'], name='answer_key__created_2e1276_idx'),
        ),
        migrations.AddIndex(
            model_name='answerkeyrow',
            index=models.Index(fields=['created_by', 'source_client_id'], name='answer_key__created_a0f186_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerkeyrow',
            unique_together={('created_by', 'client_id')},
        ),
    ]
