# Generated by Django 6.0 on 2026-06-15 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_answerkeysource_answerkeyrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=200)),
                ('vacantes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_vacantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programa_vacantes',
                'ordering': ['programa'],
                'indexes': [models.Index(fields=['created_by', 'programa'], name='programa_va_created_c69ebe_idx')],
                'unique_together': {('created_by', 'programa')},
            },
        ),
    ]
