# Generated by Django 6.0 on 2026-06-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_programavacante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('correct_value', models.DecimalField(decimal_places=3, default=10, max_digits=8)),
                ('incorrect_value', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('blank_value', models.DecimalField(decimal_places=3, default=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calification_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calification_configs',
                'ordering': ['area'],
                'indexes': [models.Index(fields=['created_by', 'area'], name='calificatio_created_8308d7_idx')],
                'unique_together': {('created_by', 'area')},
            },
        ),
    ]
