# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0008_calificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkeysource',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='answerkeyrow',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
