# Generated by Django 6.0 on 2026-06-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_answer_key_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='datformatconfig',
            name='response_answers_offset',
            field=models.IntegerField(default=7),
        ),
    ]
