# Generated by Django 6.0 on 2026-04-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='convocatorias.convocatoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procesos_calificacion',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AreaCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('correct_value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('incorrect_value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('blank_value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('plantilla_id', models.IntegerField(blank=True, null=True)),
                ('plantilla_name', models.CharField(blank=True, max_length=200)),
                ('plantilla_snapshot', models.JSONField(default=list)),
                ('total_candidates', models.IntegerField(default=0)),
                ('missing_responses', models.IntegerField(default=0)),
                ('missing_keys', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('answers_length', models.IntegerField(default=60)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='resultados.procesocalificacion')),
            ],
            options={
                'db_table': 'areas_calificacion',
                'ordering': ['area'],
                'unique_together': {('proceso', 'area')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('paterno', models.CharField(blank=True, max_length=100)),
                ('materno', models.CharField(blank=True, max_length=100)),
                ('nombres', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('programa', models.CharField(blank=True, max_length=200)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.IntegerField(default=0)),
                ('position_in_programa', models.IntegerField(default=0)),
                ('is_ingresante', models.BooleanField(default=False)),
                ('area_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='resultados.areacalificacion')),
            ],
            options={
                'db_table': 'resultados_candidatos',
                'ordering': ['position'],
                'unique_together': {('area_result', 'dni')},
            },
        ),
    ]
