# Generated by Django 6.0 on 2026-04-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadocandidato',
            name='answers_raw',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='resultadocandidato',
            name='aula',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadocandidato',
            name='cor_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resultadocandidato',
            name='correct_answers_raw',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='resultadocandidato',
            name='litho',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadocandidato',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
