# Generated by Django 6.0 on 2026-04-15 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_add_detail_fields_to_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificadorSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla_id', models.IntegerField(blank=True, null=True)),
                ('plantilla_name', models.CharField(blank=True, max_length=200)),
                ('plantilla_snapshot', models.JSONField(default=list)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('programa', models.CharField(blank=True, max_length=200)),
                ('answers', models.CharField(blank=True, default='', max_length=300)),
                ('correct_answers', models.CharField(blank=True, default='', max_length=300)),
                ('correct_value', models.DecimalField(decimal_places=3, default=10, max_digits=8)),
                ('incorrect_value', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('blank_value', models.DecimalField(decimal_places=3, default=2, max_digits=8)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificador_sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verificador_sesiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
