# Generated by Django 6.0 on 2026-04-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_add_verificador_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificadorsesion',
            name='aula',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verificadorsesion',
            name='posicion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='verificadorsesion',
            name='proceso',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='verificadorsesion',
            name='tipo_prueba',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
