# Generated by Django 6.0 on 2026-06-22 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0005_remove_convocatoria_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesocalificacion',
            name='local_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resultadocandidato',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='procesocalificacion',
            constraint=models.UniqueConstraint(fields=('created_by', 'local_id'), name='unique_proceso_local_id_per_user'),
        ),
    ]
