# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0006_alter_procesocalificacion_local_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesocalificacion',
            name='process_type',
            field=models.CharField(default='simulacro', max_length=20),
        ),
        migrations.AddField(
            model_name='procesocalificacion',
            name='simulacro_scope',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='areacalificacion',
            name='duplicate_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='areacalificacion',
            name='invalid_candidates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='areacalificacion',
            name='missing_programs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='areacalificacion',
            name='invalid_response_types',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='areacalificacion',
            name='unlinked_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='areacalificacion',
            name='no_calificados',
            field=models.JSONField(default=list),
        ),
    ]
